spring:
  datasource:
    username: root
    password: nFNWD8a7KSaLLbDaN2uO
#    url: jdbc:mysql://localhost:3307/music
#    连接云数据库
    url: jdbc:mysql://containers-us-west-109.railway.app:6390/music
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
  # 最大上传的文件大小
  max-http-header-size: 1024000
mybatis:
  mapper-locations: classpath:/mappers/*
logging:
  level:
    root: debug
